- name: install pymsql and crypto library
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMysql

- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start and enable mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true 

- name: check root password
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: mysql.devopsaws82s.online
  register: mysql_info
  ignore_errors: true 

- name: print the output
  ansible.builtin.debug:
    msg: "mysql info: {{ mysql_info }}" 

- name: set root password
  ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
  when: mysql_info.failed is true