- name: remove existing directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # /app for backend and /usr/share/nginx/html/ for frontend 
    state: absent

- name: create directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # /app for backend and /usr/share/nginx/html/ for frontend 
    state: directory

- name: download application code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCATION }}"
    remote_src: yes